version: '3'
services:
  website:
    stdin_open: true
    build:
      context: ./website
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - .:/usr/src/app
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   depends_on:
  #     - website
