version: '3'
services:
  client:
    stdin_open: true
    ports:
      - 3000:3000
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - ./client:/usr/src/app
